<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-28">

<title>How has the U.S. labor market changed over the past 40 years? – Student Name</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-6b423f165eeea3787de40cb4f8e821c3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Student Name</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../bio.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">How has the U.S. labor market changed over the past 40 years?</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Data Visualization</div>
    <div class="quarto-category">Labor Market</div>
    <div class="quarto-category">Occupation Structure</div>
    <div class="quarto-category">Task-based Model</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 28, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="frontpage.jpg" class="img-fluid figure-img" width="900"></p>
<figcaption>frontpage</figcaption>
</figure>
</div>
<section id="question-and-motivation" class="level2">
<h2 class="anchored" data-anchor-id="question-and-motivation">1. Question and Motivation</h2>
<p>The U.S. labor market looks very different from it did in the 1980s. Some types of jobs have become much more common, while others have become less common. Wages have also changed differently across occupations.</p>
<p>This leads to my question:</p>
<blockquote class="blockquote">
<p><strong>How has the occupational structure of the U.S. labor market changed since the 1980s, and how have real wages evolved across different types of occupations?</strong></p>
</blockquote>
<p>To solve this problem, I focus on 4 types of occupations based on the tasks workers perform in this project: <strong>Non-Routine Cognitive, Routine Cognitive, Routine Manual, and Non-Routine Manual</strong>. I use descriptive statistics and visualizations to compare employment shares and real wages from 1983 to 2023.</p>
</section>
<section id="data-processing" class="level2">
<h2 class="anchored" data-anchor-id="data-processing">2. Data Processing</h2>
<p>I use microdata from the <strong>IPUMS Current Population Survey (CPS)</strong> from 1983 to 2023. The CPS provides information on employment, occupations, income, and other characteristics of U.S. workers.</p>
<p>To study changes in the occupational structure of the labor market, I focus on <strong>employed workers ages 25–64</strong>. This helps me focus on people who are more likely to be in the working-age population and reduces the influence of people who are still in school or close to retirement.</p>
<p>For wages, I use reported <code>annual wage income</code> and adjust it for inflation using the <code>CPI-U</code>, so that all wages are expressed in <code>2023 dollars</code>. I then calculate the <code>weighted median real wage</code> for each occupational group and year.</p>
<p>Because the CPS is a survey, I use the ASEC sampling weight (<code>ASECWT</code>) when calculating employment shares and median wage statistics. This allows the results to better represent the U.S. population covered by the survey rather than simply reflecting the number of observations in my sample.</p>
</section>
<section id="the-standard-task-based-model" class="level2">
<h2 class="anchored" data-anchor-id="the-standard-task-based-model">3. The Standard Task-based Model</h2>
<p>To organize occupations, I use the <code>standard task-based model(Autor, Levy, and Murnane 2003)</code>, a classic framework in labor economics.</p>
<p>The basic idea is simple: instead of thinking about jobs only as “high-skill” or “low-skill,” we can think about the different tasks that workers perform. The key idea is that an occupation can be viewed as a <strong>bundle of tasks</strong>, and production depends on combining different types of tasks.</p>
<p>These tasks can be classified along two dimensions. The first is whether the work is mainly <strong>cognitive or manual</strong>, and the second is whether the tasks are <strong>routine or non-routine</strong>.</p>
<p>The <strong>cognitive or manual</strong> dimension captures whether a job relies mainly on problem-solving, judgment, and information processing or on physical and manual activities.</p>
<p>The <strong>routine or non-routine</strong> dimension captures whether tasks are repetitive and can be clearly specified by rules and procedures, or whether they require flexibility and are more difficult to codify and automate.</p>
<p>Using the IPUMS <code>OCC1990 occupation classification</code>, I group occupations into four task categories: <strong>Non-Routine Cognitive</strong>, <strong>Routine Cognitive</strong>, <strong>Routine Manual</strong>, and <strong>Non-Routine Manual</strong>. The detailed occupation mapping and sample construction are described in the accompanying code.</p>
<section id="four-types-of-occupations-based-on-tasks" class="level3">
<h3 class="anchored" data-anchor-id="four-types-of-occupations-based-on-tasks">3.1 Four Types of Occupations Based on Tasks</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Task Type</th>
<th style="text-align: left;">Key Features</th>
<th style="text-align: left;">Examples</th>
<th style="text-align: left;">Impact of Technology / AI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Cognitive Routine</strong></td>
<td style="text-align: left;">Repetitive tasks that follow clear rules and procedures.</td>
<td style="text-align: left;">Bank tellers, data entry clerks, entry-level accountants</td>
<td style="text-align: left;"><strong>More exposed to automation</strong> through software, algorithms, and AI.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Manual Routine</strong></td>
<td style="text-align: left;">Repetitive physical tasks that follow fixed procedures.</td>
<td style="text-align: left;">Assembly-line workers, warehouse sorters, machine operators</td>
<td style="text-align: left;"><strong>More exposed to replacement</strong> by robots and automated equipment.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Cognitive Non-Routine</strong></td>
<td style="text-align: left;">Tasks requiring creativity, problem-solving, judgment, and communication.</td>
<td style="text-align: left;">Researchers, software architects, managers, physicians</td>
<td style="text-align: left;"><strong>Technology can complement these tasks</strong> and increase productivity.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Manual Non-Routine</strong></td>
<td style="text-align: left;">Physical tasks requiring flexibility, spatial awareness, and adaptation to changing environments.</td>
<td style="text-align: left;">Cleaners, caregivers, restaurant workers, truck drivers</td>
<td style="text-align: left;"><strong>Difficult to automate completely</strong> because tasks are harder to standardize.</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="data-descriptive-analysis" class="level2">
<h2 class="anchored" data-anchor-id="data-descriptive-analysis">4. Data Descriptive Analysis</h2>
<section id="a-employment-share" class="level3">
<h3 class="anchored" data-anchor-id="a-employment-share">(a) Employment Share</h3>
<p>The table below shows the employment share of each occupational group at five-year intervals.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th style="text-align: right;">Non-Routine Cognitive</th>
<th style="text-align: right;">Routine Cognitive</th>
<th style="text-align: right;">Routine Manual</th>
<th style="text-align: right;">Non-Routine Manual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1983</td>
<td style="text-align: right;">31.8%</td>
<td style="text-align: right;">27.7%</td>
<td style="text-align: right;">29.0%</td>
<td style="text-align: right;">11.4%</td>
</tr>
<tr class="even">
<td>1988</td>
<td style="text-align: right;">33.1%</td>
<td style="text-align: right;">27.4%</td>
<td style="text-align: right;">28.1%</td>
<td style="text-align: right;">11.4%</td>
</tr>
<tr class="odd">
<td>1993</td>
<td style="text-align: right;">35.0%</td>
<td style="text-align: right;">27.5%</td>
<td style="text-align: right;">25.5%</td>
<td style="text-align: right;">12.0%</td>
</tr>
<tr class="even">
<td>1998</td>
<td style="text-align: right;">36.9%</td>
<td style="text-align: right;">26.2%</td>
<td style="text-align: right;">25.3%</td>
<td style="text-align: right;">11.6%</td>
</tr>
<tr class="odd">
<td>2003</td>
<td style="text-align: right;">38.2%</td>
<td style="text-align: right;">25.9%</td>
<td style="text-align: right;">22.9%</td>
<td style="text-align: right;">13.1%</td>
</tr>
<tr class="even">
<td>2008</td>
<td style="text-align: right;">39.2%</td>
<td style="text-align: right;">24.7%</td>
<td style="text-align: right;">22.6%</td>
<td style="text-align: right;">13.5%</td>
</tr>
<tr class="odd">
<td>2013</td>
<td style="text-align: right;">41.2%</td>
<td style="text-align: right;">23.4%</td>
<td style="text-align: right;">20.6%</td>
<td style="text-align: right;">14.8%</td>
</tr>
<tr class="even">
<td>2018</td>
<td style="text-align: right;">43.7%</td>
<td style="text-align: right;">21.1%</td>
<td style="text-align: right;">21.0%</td>
<td style="text-align: right;">14.2%</td>
</tr>
<tr class="odd">
<td>2023</td>
<td style="text-align: right;">47.8%</td>
<td style="text-align: right;">19.6%</td>
<td style="text-align: right;">19.8%</td>
<td style="text-align: right;">12.8%</td>
</tr>
</tbody>
</table>
</section>
<section id="b-median-real-wage-by-occupational-group" class="level3">
<h3 class="anchored" data-anchor-id="b-median-real-wage-by-occupational-group">(b) Median Real Wage by Occupational Group</h3>
<p>The table below shows the weighted median real wage at five-year intervals. All values are in 2023 dollars.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th style="text-align: right;">Non-Routine Cognitive</th>
<th style="text-align: right;">Routine Cognitive</th>
<th style="text-align: right;">Routine Manual</th>
<th style="text-align: right;">Non-Routine Manual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1983</td>
<td style="text-align: right;">$62,715</td>
<td style="text-align: right;">$39,770</td>
<td style="text-align: right;">$48,948</td>
<td style="text-align: right;">$24,474</td>
</tr>
<tr class="even">
<td>1988</td>
<td style="text-align: right;">$69,543</td>
<td style="text-align: right;">$41,211</td>
<td style="text-align: right;">$51,513</td>
<td style="text-align: right;">$25,757</td>
</tr>
<tr class="odd">
<td>1993</td>
<td style="text-align: right;">$67,477</td>
<td style="text-align: right;">$42,173</td>
<td style="text-align: right;">$46,391</td>
<td style="text-align: right;">$25,304</td>
</tr>
<tr class="even">
<td>1998</td>
<td style="text-align: right;">$69,165</td>
<td style="text-align: right;">$42,995</td>
<td style="text-align: right;">$46,874</td>
<td style="text-align: right;">$28,040</td>
</tr>
<tr class="odd">
<td>2003</td>
<td style="text-align: right;">$74,520</td>
<td style="text-align: right;">$46,600</td>
<td style="text-align: right;">$49,680</td>
<td style="text-align: right;">$32,115</td>
</tr>
<tr class="even">
<td>2008</td>
<td style="text-align: right;">$73,379</td>
<td style="text-align: right;">$44,841</td>
<td style="text-align: right;">$48,118</td>
<td style="text-align: right;">$31,135</td>
</tr>
<tr class="odd">
<td>2013</td>
<td style="text-align: right;">$73,247</td>
<td style="text-align: right;">$44,471</td>
<td style="text-align: right;">$45,779</td>
<td style="text-align: right;">$30,083</td>
</tr>
<tr class="even">
<td>2018</td>
<td style="text-align: right;">$75,718</td>
<td style="text-align: right;">$46,111</td>
<td style="text-align: right;">$48,537</td>
<td style="text-align: right;">$31,064</td>
</tr>
<tr class="odd">
<td>2023</td>
<td style="text-align: right;">$75,000</td>
<td style="text-align: right;">$46,000</td>
<td style="text-align: right;">$48,000</td>
<td style="text-align: right;">$35,000</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="data-visualization" class="level2">
<h2 class="anchored" data-anchor-id="data-visualization">5. Data Visualization</h2>
<p><strong>(1) The occupational structure has shifted toward non-routine cognitive work</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figure1.png" class="img-fluid figure-img" width="900"></p>
<figcaption>Figure1</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figure2.png" class="img-fluid figure-img" width="900"></p>
<figcaption>Figure2</figcaption>
</figure>
</div>
<p>Figure 1 and Figure 2 shows the employment share of the four occupational groups from 1983 to 2023.</p>
<p><strong>Non-Routine Cognitive</strong> employment increased steadily, from about one-third of employment in 1983 to almost one-half in 2023.</p>
<p>At the same time, both <strong>Routine Cognitive</strong> and <strong>Routine Manual</strong> jobs became a smaller share of total employment.</p>
<p>In contrast, <strong>Non-Routine Manual</strong> employment remained relatively stable for much of the period and increased somewhat around the late 2000s and early 2010s before declining slightly toward 2023.</p>
<p>Overall, the figure suggests a long-run shift in the composition of employment. The U.S. labor market has become increasingly concentrated in non-routine cognitive occupations, while routine forms of cognitive and manual work have become relatively less common.</p>
<p>Technology is one possible explanation for this pattern because computers, especially artificial intelligence, can replace some routine tasks while complementing work that involves problem-solving and judgment.</p>
<p><strong>(2) Wage growth has differed substantially across occupational groups</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figure3.png" class="img-fluid figure-img" width="900"></p>
<figcaption>Figure3</figcaption>
</figure>
</div>
<p>Figure 3 compares the cumulative growth in the real median annual wage, with each group normalized to <strong>100 in 1983</strong>. Also, the wage measure is adjusted for inflation using CPI-U and expressed <strong>in 2023 dollars</strong>.</p>
<p>The largest increase is in <strong>Non-Routine Manual</strong> occupations, reaching roughly <strong>143</strong> relative to its 1983’s 100. One possible explanation is that many occupations in this group are concentrated in the service sector, which has expanded substantially over the past several decades.</p>
<p><strong>Non-Routine Cognitive</strong> wages also increased substantially, reaching around <strong>120</strong>. <strong>Routine Cognitive</strong> wages rose more moderately, to around <strong>115</strong>.</p>
<p><strong>Routine Manual</strong> occupations show a very different pattern. Their real median wage fluctuated considerably over the period and ended <strong>slightly below their 1983 level</strong>. This pattern may be related to technological change, as routine manual tasks are often easier to automate or replace with technology. At the same time, globalization and changes in the demand for different types of labor may have also contributed to the relatively weak wage growth in these occupations.</p>
<p>This is an important result because it shows that employment growth and wage growth do not move together in a simple way. Non-Routine Cognitive employment expanded the most in terms of employment share, but Non-Routine Manual occupations experienced the largest cumulative real wage growth in this comparison.</p>
<p>The shaded recession periods also show that wage trends can fluctuate around major economic downturns. However, the long-run differences between occupational groups are more important than any single short-term movement.</p>
<p><strong>(3) What do these changes look like in actual wage levels?</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figure4.png" class="img-fluid figure-img" width="900"></p>
<figcaption>Figure4</figcaption>
</figure>
</div>
<p>The previous figure 3 focuses on wage growth relative to 1983. It is useful for comparing how quickly wages changed across occupational groups, but it doesn’t show the actual level of earnings.</p>
<p>Figure 4 compares the actual median real wage in 1983 and 2023. The left point shows the 1983 wage, while the right point shows the 2023 wage. The connecting line shows the change over the 40-year period, and the percentage next to the 2023 point shows the cumulative real wage growth. The figure uses the same weighted median real wage measure as the previous analysis.</p>
<p>The comparison reveals clear differences in both wage levels and wage growth:</p>
<p><strong>Non-Routine Cognitive</strong> occupations had the highest median real wage in both years, increasing from <strong>$62,715 in 1983 to $75,000 in 2023</strong>, a 19.6% increase.</p>
<p><strong>Routine Cognitive</strong> wages also increased, from <strong>$39,770 to $46,000</strong>, a 15.7% increase.</p>
<p>In contrast, <strong>Routine Manual</strong> wages changed very little, declining slightly from <strong>$48,948 to $48,000</strong>, a decline of about 1.9%.</p>
<p><strong>Non-Routine Manual</strong> group shows the largest proportional increase, with median real wages rising from $24,474 to $35,000, a 43.0% increase. However, it still had the lowest median wage level in 2023. This highlights an important distinction: a group can experience relatively strong wage growth while starting from a lower wage level and still earning less than other groups.</p>
<p>Together, Figures 3 and 4 provide a more complete picture of wage inequality across occupations. Figure 3 shows how quickly wages changed relative to each group’s starting point, while Figure 4 shows the actual wage levels in 1983 and 2023. Looking at both measures helps distinguish between <strong>relative wage growth</strong> and <strong>absolute wage levels</strong>.</p>
</section>
<section id="what-do-these-results-tell-us" class="level2">
<h2 class="anchored" data-anchor-id="what-do-these-results-tell-us">6. What Do These Results Tell Us?</h2>
<p>The results point to three findings.</p>
<p><strong>First, the composition of employment changed substantially.</strong> Over the past 40 years, the U.S. labor market has shifted strongly toward Non-Routine Cognitive occupations, while routine cognitive and routine manual work have become smaller parts of total employment.</p>
<p><strong>Second, real wage growth differed across occupational groups.</strong> Non-Routine Cognitive occupations continued to have the highest wage levels, Non-Routine Manual occupations had the largest percentage increase, while Routine Manual occupations had almost no long-run growth.</p>
<p><strong>Third, employment growth and wage growth were not the same thing.</strong> The occupation group that expanded the most was not the group with the largest proportional increase in wages.</p>
<p>The main takeaway is that the U.S. labor market did not change in just one aspect. Both the types of jobs people do and the wages associated with those jobs have changed. Looking at both employment shares and wages gives a clearer picture of how the labor market has evolved since the 1980s.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><img src="../../..\images/UniversityofPennsylvania_FullLogo_RGB.png" class="img-fluid" width="100"></p>
</div>   
    <div class="nav-footer-center">
<p>© 2026 Student Name</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>